### ISSUE TITLE
MySQL Spam

### ISSUE THREAD

**Issue by TNTUP** [ezeiger92/Prism-Bukkit#4]
Since today, I'm getting console spam worth of 1.9GB of this

20:06:42 Prism]:: Database connection error: '2.157982635E9' in column '1' is outside valid range for the datatype INTEGER.
20:06:42 CONSOLE: WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.157982635E9' in column '1' is outside valid range for the datatype INTEGER.
20:06:42 CONSOLE: WARN]: at sun.reflect.GeneratedConstructorAccessor221.newInstance(Unknown Source)
20:06:42 CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:06:42 CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.ResultSetImpl.throwRangeException(ResultSetImpl.java:7061)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.ResultSetImpl.parseIntAsDouble(ResultSetImpl.java:6339)
20:06:42 CONSOLE: WARN]: at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2509)
20:06:42 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.insertExtraData(RecordingTask.java:336)
20:06:42 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:275)
20:06:42 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:37)
20:06:42 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:377)
20:06:42 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
20:06:42 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
20:06:42 CONSOLE: WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
20:06:42 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:06:42 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:06:42 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
20:06:42 CONSOLE: WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.157982636E9' in column '1' is outside valid range for the datatype INTEGER.
20:06:42 CONSOLE: WARN]: at sun.reflect.GeneratedConstructorAccessor221.newInstance(Unknown Source)
20:06:42 CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:06:42 CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
20:06:43 CONSOLE: WARN]: at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:275)
20:06:43 CONSOLE: WARN]: at me.botsko.prism.actionlibs.QueueDrain.forceDrainQueue(QueueDrain.java:37)
20:06:43 CONSOLE: WARN]: at me.botsko.prism.Prism.onDisable(Prism.java:1062)
20:06:44 CONSOLE: WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
20:06:44 CONSOLE: WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
20:06:44 CONSOLE: WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:425)
20:06:44 CONSOLE: WARN]: at com.ryanclancy000.plugman.utilities.Utilities.unloadPlugin(Utilities.java:422)
20:06:44 CONSOLE: WARN]: at com.ryanclancy000.plugman.utilities.Utilities.unloadCommand(Utilities.java:373)
20:06:44 CONSOLE: WARN]: at com.ryanclancy000.plugman.PlugManCommands.onCommand(PlugManCommands.java:72)
20:06:44 CONSOLE: WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20:06:44 CONSOLE: WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
20:06:44 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
20:06:44 CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:06:44 CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
20:06:44 CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
20:06:44 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)

and the DB size is worth of 363GB and I wish not to RESET nor DELETE because I want to keep the history of block edits like 2-4 years... but planning to delete it completely at Sep 16. 

Compiled your plugin and using it (will restart if all fails) with plugman and no avail. I'm aware Prism is a huge unsupported plugin but thats the most reliable I ever find in that time when LogBlock couldn't log entities, nor CoreProtect in 2013 so I kept Prism.

**Comment by ezeiger92** [comment]
I don't think I touched anything that would have caused this, were you having this issue with an unmodified prism?

**Comment by ezeiger92** [comment]
That is not tested, don't trust it yet :P

**Comment by TNTUP** [comment]
I was using GPrism build since a year from now on. I tried yours no luck and also the /pr i was broke aswell so I've reverted to GPrism

**Comment by ezeiger92** [comment]
You had so many entries that the ids didn't fit into a java int, which would break most of the plugin.

I've changed my fork to use long/bigint for ids, which should fix your problem but will also modify the database in a way that might not be backwards compatible. After that patch, I had no trouble using the inspect wand, lookups, and rollbacks even with large ids.

If you want to stick with GPrism, I'll close this ticket because it should be fixed and I have no reasonable way to test a database as large as yours. If you want to try this fork again, I'll wait for confirmation that it's fixed.

**Comment by TNTUP** [comment]
Well, in the midnight I tried fixing the console errors and the issue with the column '1' which is the ID, is a INT and I could add new lines in PMA, which Prism cannot... Even looking up it couldn't but I could view in PMA. Even in prism_data_extra I was able to add a newline without issues. I've did a dirty fix by following stacktraces on console and it seems to get to work again (logs everything at least I hope and lookup works) I'll be sure trying this build later.

Just to note, since it wont be backwards with GPrism, does your fix (hope not) converts the entire database INT ids to LONG ids? If so it would take hours of downtime.. For now, Close the ticket. I'll let you know when I'm using your fork! Thanks for your time and great help

**Comment by ezeiger92** [comment]
Right now it changes the database to use BIGINT (long). I could revert that part because the database uses unsigned int values and this problem came from java failing to read signed ints.

Alternatively you could set meta.schema_ver to 6 before launching prism, and then it wouldn't attempt to modify the database.

At any rate, glad to help out. I wasn't expecting anyone to take a look at this fork so early, so there are likely some bugs in it. I'll try to squash them in a timely manner.

**Comment by TNTUP** [comment]
Okay^^ Thanks so much again!
