### ISSUE TITLE
1.9.x 1.10.x 1.11.x versions?

### ISSUE THREAD

**Issue by Tjird** [ezeiger92/Prism-Bukkit#7]
As the title says, are there any 1.9.x, 1.10.x and 1.11.x versions or can you make new branches with these versions? Maybe if it is simple a 1.9.x to 1.13.x compatible version.

**Comment by ezeiger92** [comment]
I'm only targeting the latest minecraft version and don't know what versions of prism support older minecraft versions, sorry.
