### ISSUE TITLE
Can't rollback dropped items

### ISSUE THREAD

**Issue by TptMike** [ezeiger92/Prism-Bukkit#8]
I'm curious if this is a Prism bug or a plugin conflict. When i do an a rollback on the drop action (item-drop also) the results are 0 reversals, x skipped. So i enabled debug and it says that it can't complete the rollback because the player (me) is offline. Below is the debug from the executed command

https://pastebin.com/bmEWeMjV

Running a build compiled against the latest commit at the time: https://github.com/ezeiger92/Prism-Bukkit/commit/4bf522190bede24edec43178eb329b6b7f67e70c

Thanks for your help!

**Comment by ezeiger92** [comment]
Somehow the player uuid was never grabbed from prism results when doing a rollback. Wow

**Comment by ezeiger92** [comment]
a09a370ebb95c065382204312f8d91f3f8f8da57 may fix it, but I'm not able to test at the moment.

**Comment by Tjird** [comment]
Tested, Lookup doens't work now. https://pastebin.com/mseTiPi2
Saw that the datatype in table prism_players column player_uuid binary(10) is, also can't query a select statement in the prism_players table.
Spigot 1.13.1

**Comment by ezeiger92** [comment]
Lol, brilliant. I really need to get my test server up again

**Comment by ezeiger92** [comment]
It wasn't even the uuids, it was that I removed the fallback "I don't know what slot this was in" rollback for items back when messing with item frames and armor stands. -_-
